### ISSUE TITLE
crash in android 

### ISSUE THREAD

**Issue by mataoct** [halilb/react-native-photo-browser#28]
10-28 14:49:28.929 14806-14806/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.photobrowserexample, PID: 14806
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.photobrowserexample/com.photobrowserexample.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2343)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:193)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
                                                       at com.facebook.react.ReactActivity.getReactNativeHost(ReactActivity.java:79)
                                                       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:107)
                                                       at android.app.Activity.performCreate(Activity.java:5283)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                       at android.os.Looper.loop(Looper.java:193) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by mataoct** [comment]
I fix it myself,
it caused by react-native 0.2.9
`https://blog.yourtion.com/update-react-native-029-bug.html`

**Comment by halilb** [comment]
Thanks for the report and happy for the fix @mataoct .
